name = "KJW's Tracking"
prefix = "KJW_Tracking"
author = "KJW"
mainprefix = "y"

[files]
include = [
    "mod.cpp",
    "*.paa"
]

[version]
git_hash = 0 # Disabled

path = "addons/core/script_version.hpp" # Default